### PR TITLE
Stop this.

### PR DESCRIPTION
**Pull request by MemeHoovy**
Seriously, you just keep bloating your engine with a bunch of useless garbage, I've had enough of it, what do you think your trying to do? Who are you trying to impress by filling up your engine with useless shit your not gonna use? What your doing right now just needs to **stop**. You need to cleanup your engine, remove all the useless bullcrap you added, or better, start everything fresh because you bloated it up to the goddamn brim. Your engine is eventually gonna topple over itself because of the amount of crap you added. You just can't have everything Joalor, I made the same mistake like you, adding useless features & such, and eventually, **everything broke on me & I had to start over.** So, to basically put it, stop adding useless shit to your engine that nobody wants, and add features people actually want, instead of what **you** want.

With all due respect to you Joalor & not hating on you specifically -MemeHoovy

### CODE REVIEW

**Comment by Joalor64GH** [comment]
um okay

**Comment by MemeHoovy** [comment]
> um okay

Hey look, sorry If I've been a bit toxic, I've had an experience where my engine just broke down on me where I added so much crap it just...broke, and I don't want you to share the same experience with me.

**Comment by Joalor64GH** [comment]
Okay, this makes sense. I should probably stop bloating my engine anyways. 👍

**Comment by MemeHoovy** [comment]
Thank god, because you bloating out your engine is just eventually a disaster waiting to happen.

**Pull request merged**
